name: Create Release For Tag

on:
  push:
    tags: # Set this to the tags you want to release for
      - "v*"

permissions:
  contents: write

jobs:
  changeset:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: # fetch-depth 0 is required so we can get the last tag and extract the changelog from the previous commit
          fetch-depth: 0

      - name: Set tag and previous tag
        id: set-tags
        run: |
          echo "previous_tag=$(git describe --tags --abbrev=0 ${GITHUB_REF#refs/*/}^)" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          | # in this the RELEASE_NOTES are built line by line and +=$ syntax is used so that the \n newlines are correctly interpreted as newlines ratehr than string literals
          PREVIOUS_TAG="${{ steps.set-tags.outputs.previous_tag }}"
          GIT_TAG="${{ steps.set-tags.outputs.tag }}"
          BODY=$(git show HEAD -- CHANGELOG.md | grep '^+[^+]' | sed 's/^+//')

          RELEASE_NOTES="## What's Changed"
          RELEASE_NOTES+=$'\n'"${BODY}"
          RELEASE_NOTES+=$'\n\n'"**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...${GIT_TAG}"

          # Echo the tag and the formatted body for debugging purposes
          echo "Tag: ${GIT_TAG}"
          echo "Previous Tag: ${PREVIOUS_TAG}"
          echo "Release Notes: ${RELEASE_NOTES}"

          # Use the GitHub CLI (gh) to create a new release with the formatted release notes
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases \
            -f "tag_name=${GIT_TAG}" \
            -f "name=${GIT_TAG}" \
            -f "body=${RELEASE_NOTES}" \
            -F "draft=false" \
            -F "prerelease=false" \
            -F "generate_release_notes=false"
